apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookstore.fullname" . }}-nginx-conf
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap.nginx }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
