apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookstore.fullname" . }}-app-config
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap.app }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
