apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}-worker
  labels:
    app: {{ include "bookstore.fullname" . }}-worker
    {{- include "bookstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  selector:
    app: {{ include "bookstore.fullname" . }}-worker
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: 8090
      protocol: TCP
      name: http
